const IPC_EVENT_REQUEST_STATE = 'IPC_EVENT_REQUEST_STATE';
const IPC_EVENT_SEND_STATE = 'IPC_EVENT_SEND_STATE';
const IPC_EVENT_STATE_CHANGE = 'IPC_EVENT_STATE_CHANGE';
const IPC_EVENT_FILES_ADDED = 'IPC_EVENT_FILES_ADDED';
const IPC_EVENT_NOTIFICATION = 'IPC_EVENT_NOTIFICATION';
const IPC_EVENT_HIDE_MENU = 'IPC_EVENT_HIDE_MENU';
const IPC_EVENT_QUIT_APP = 'IPC_EVENT_QUIT_APP';
const IPC_EVENTS = {
    IPC_EVENT_REQUEST_STATE,
    IPC_EVENT_SEND_STATE,
    IPC_EVENT_STATE_CHANGE,
    IPC_EVENT_FILES_ADDED,
    IPC_EVENT_NOTIFICATION,
    IPC_EVENT_HIDE_MENU,
    IPC_EVENT_QUIT_APP,
};

module.exports = {
    IPC_EVENT_REQUEST_STATE,
    IPC_EVENT_SEND_STATE,
    IPC_EVENT_STATE_CHANGE,
    IPC_EVENT_FILES_ADDED,
    IPC_EVENT_NOTIFICATION,
    IPC_EVENT_HIDE_MENU,
    IPC_EVENT_QUIT_APP,
    IPC_EVENTS,
};
